### PR TITLE
Fix for #15: Improved rule documentation

### LINKED ISSUE #15: Improve rule documentation
In sonar-qube good plugins only ship rules that include documentation with a BAD and a GOOD example as well as some explanation/rationale.
We should follow this best practice for all our rules.
See also https://github.com/devonfw/my-thai-star/issues/152

### PR DESCRIPTION
**Pull request by lmarniazman**
Resolves #15:
- Added html and json files for every rule
  - The DevonSonarDefinition class had to be changed a little for it to get the rule metadata from the json files and not from the rule annotations like before
- Improved description of rules
- Added code examples

### CODE REVIEW

File: src/main/java/com/devonfw/ide/sonarqube/common/impl/check/component/DevonArchitectureComponentDeclarationCheck.java [hunk 1]
```diff
@@ -15,9 +14,10 @@
  * {@link DevonArchitectureComponentCheck} verifying that a {@link Component} itself is properly defined in
  * {@link Architecture} and that the general {@link Component#getDependencies() dependencies} are not violated.
  */
-@Rule(key = "Devon4j:C1", name = "Devon Component Declaration Check", //
-    description = "Verify component is properly declared in architecture.json file.", //
-    priority = Priority.CRITICAL, tags = { "architecture-violation", "devonfw", "component" })
+// @Rule(key = "Devon4j:C1", name = "Devon Component Declaration Check", //
+// description = "Verify component is properly declared in architecture.json file.", //
+// priority = Priority.CRITICAL, tags = { "architecture-violation", "devonfw", "component" })
+@Rule(key = "C1")
```
Comment (hohwille) [inline src/main/java/com/devonfw/ide/sonarqube/common/impl/check/component/DevonArchitectureComponentDeclarationCheck.java]: Why do we have to change the rule keys? We have references to them in external files that you did not change and that will break with the PR.
Also the key of a rule has IMHO to be unique all across SonarQube. How can we assure that without a namespace like `Devon4j:`?
Existing rules from SonarQube are called `Squid:«number»`. I considered the rules keys from the makers of SonarQube as a kind of best-practice to follow.
If you have good reasons to change the keys please explain here. Otherwise I would suggest to keep the old keys.

File: src/main/java/com/devonfw/ide/sonarqube/common/impl/check/component/DevonArchitectureComponentDeclarationCheck.java [hunk 2]
```diff
@@ -15,9 +14,10 @@
  * {@link DevonArchitectureComponentCheck} verifying that a {@link Component} itself is properly defined in
  * {@link Architecture} and that the general {@link Component#getDependencies() dependencies} are not violated.
  */
-@Rule(key = "Devon4j:C1", name = "Devon Component Declaration Check", //
-    description = "Verify component is properly declared in architecture.json file.", //
-    priority = Priority.CRITICAL, tags = { "architecture-violation", "devonfw", "component" })
+// @Rule(key = "Devon4j:C1", name = "Devon Component Declaration Check", //
+// description = "Verify component is properly declared in architecture.json file.", //
+// priority = Priority.CRITICAL, tags = { "architecture-violation", "devonfw", "component" })
```
Comment (hohwille) [inline src/main/java/com/devonfw/ide/sonarqube/common/impl/check/component/DevonArchitectureComponentDeclarationCheck.java]: Clean code. Please stop the habbit of committing outcommented code. We have the git history if we need to look up something from the past.

**Comment by lmarniazman** [comment]
@hohwille Thanks for the feedback :+1:

It's true that the json files don't really add any value, as we could just keep this metadata in the annotations. I will test if they are necessary when there are html files present, but I would think not. I think your suggestion of keeping both the rule annotation and the json file is a good idea, as we can then use the json to put in larger strings like the description. With a solution like this the rule annotation won't be as bloated anymore and we can easily add more attributes to the rule at will.

As for the html files, I would be happy to go through them together and think about some changes.

File: src/main/java/com/devonfw/ide/sonarqube/common/impl/check/component/DevonArchitectureComponentDeclarationCheck.java (hunk 1 above)
Comment (lmarniazman) [reply src/main/java/com/devonfw/ide/sonarqube/common/impl/check/component/DevonArchitectureComponentDeclarationCheck.java]: The problem with the external files is a good point, haven't thought of that. As for the uniqueness of the rules: Our rules are saved under our repository key `devon-java`, so e.g. this rule will be shown in SonarQube as `devon-java:C1`. The SonarQube rules probably belong to the repository `Squid`. Would it suffice for the external files to maybe change our repository key to `Devon4j`? Then our rules would still have the same name as they had before.

**Comment by lmarniazman** [comment]
I honestly think that we will be fine without the json files. We don't really need a description for the rule as we have that in the created issue message and in the html of the rule. Everything else will be fine in the annotation.
